version: '3'

services:
  gh-pages:
    entrypoint:
      - "jekyll"
      - "serve"
      - "--verbose"
      - "--force_polling"
      - "-H"
      - "0.0.0.0"
      - "-P"
      - "4000"
  gulp:
    environment:
    - USE_POLLING=1